name: "Podcast Generator"
author: "Say2hub"
description: "Generates feed for podcast"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    description: commiter's Email address
    required: true
    default: ${{github.actor}}@localhost
  name:
    description: commiter's name
    required: true
    default: ${{github.actor}}
